### ISSUE TITLE
Algunas rutas provocan errores al querer importar o usar la vista de SGit

### ISSUE THREAD

**Issue by 51lv3str1** [uqbar-project/SGit#16]
Esto sucede con mas frecuencia en Windows. Pero ejemplo, la ruta: **C:/Users/publico/Downloads/wollok-win32.win32.x86_64/workspace** provoca un fallo al querer importar el proyecto.

**Comment by npasserini** [comment]
Eso es medio un problema normal en Java, los directorios con puntos o
caracteres raros suelen traer problemas.

**Comment by 51lv3str1** [comment]
Acabo de subir a develop un posible fix de esto. Esto se puede probar usando Eclipse commiters y importando algún proyecto eclipse (Java o Wollok).
