### ISSUE TITLE
Los mensajes de errores deberían ser mas explícitos

### ISSUE THREAD

**Issue by 51lv3str1** [uqbar-project/SGit#18]
El problema es que debo capturar explicitamente el string que lanza la exception y de a partir del mensaje, lanzar uno adaptado a nuestro plugin.

**Comment by npasserini** [comment]
Hay un problema bastante común que no sé si ya está reportado en otro lado
y es un error común que intentan importar un proyecto que ya existe en el
workspace (puede ser que no esté importado pero está el directorio). Y al
hacerlo falla pero lo confuso es que el error dice algo de permisos o algo
así, muy confuso. Habría que ver si podemos detectar bien ese error y
manejarlo mejor.

**Comment by 51lv3str1** [comment]
> Hay un problema bastante común que no sé si ya está reportado en otro lado y es un error común que intentan importar un proyecto que ya existe en el workspace (puede ser que no esté importado pero está el directorio). Y al hacerlo falla pero lo confuso es que el error dice algo de permisos o algo así, muy confuso. Habría que ver si podemos detectar bien ese error y manejarlo mejor. El mar., 3 de sep. de 2019 a la(s) 17:29, 

![image](https://user-images.githubusercontent.com/11511177/75206277-cf98fa00-5754-11ea-9d01-e13a3b653fe9.png)

Esto ya esta resuelto en la versión en development.

**Comment by 51lv3str1** [comment]
Se han actualizado los mensaje ya existentes por otros mejores explicados y se agregaron muchas mas validaciones. Por lo pronto cierro este issue, ya que el trabajo a continuar es el de seguir agregando mas validaciones.
