### ISSUE TITLE
Widget is disposed

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/SGit#2]
Cuando cierro la vista de Git y empiezo a abrir archivos tira el error: Widget is disposed.

![Peek 2019-03-23 17-05](https://user-images.githubusercontent.com/4098184/54871261-0ec60a80-4d90-11e9-95cd-080842130681.gif)

Esto pasa cuando abro y cierro la vista, si no la abro nunca ó si la dejo abierta siempre no tira ningún error.

Si después de llegar al error vuelvo a abrir la vista de Git **NO** se arregla.

**Comment by 51lv3str1** [comment]
Este bug también se encuentra solucionado en la versión actual de SGit.

**Comment by 51lv3str1** [comment]
Esto cada tanto vuelve a suceder, conviene volver a ver la vista de sgit y repensar como evitar que esto pueda suceder.

**Comment by 51lv3str1** [comment]
Era un listener que quedaba seteado cuando la vista se cerraba. Ya esta fixeado.
