### ISSUE TITLE
En el menú Importar, estaría bueno que se pudiera diferenciar por nombre

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/SGit#3]
![Selección_999(161)](https://user-images.githubusercontent.com/5421992/54946241-6a220500-4f16-11e9-9528-89c7e9be6a97.png)

Es decir, ahí podría decir "Proyecto Git Simple" ó algo así, así se sabe qué plugin se está usando, y además yo tengo ganas de clickear ahí. Quizás sacar la palabra "Importar", porque no está en ninguna de las otras opciones porque todas son importar.

**Comment by 51lv3str1** [comment]
Me gusta la idea, ademas sumo que la descripción del import esta en ingles, y debería estar en español.

**Comment by 51lv3str1** [comment]
![image](https://user-images.githubusercontent.com/11511177/75171087-e1a17b00-5709-11ea-8406-5263c3d3be56.png)
Ahí lo arregle, y ademas ya incluye el arreglo de Internacionalización.
