### ISSUE TITLE
Con un proyecto al importar me dice "No value present" y no lo puedo importar

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/SGit#4]
Tanto con como sin contraseña, intento importar el siguiente repo:

https://github.com/wollok/granjavilla.git

y no anda:

![Selección_999(162)](https://user-images.githubusercontent.com/5421992/54946764-95f1ba80-4f17-11e9-8839-b68a0d013f3d.png)

![Selección_999(163)](https://user-images.githubusercontent.com/5421992/54946780-9db15f00-4f17-11e9-8068-c889eff8a54a.png)

Estoy en Linux Mint.

Versiones de Wollok y Eclipse:

![Selección_999(164)](https://user-images.githubusercontent.com/5421992/54946885-d4877500-4f17-11e9-8f37-a8612b547cbb.png)

Todo esto está probado con la versión anterior actualizada desde el diálogo. Me bajé Wollok de nuevo (El x86_64 para Linux) y el error persiste. Probé con "el sueldo de pepe" y me anda. 

https://github.com/wollok/granjavilla/issues/1

**Comment by 51lv3str1** [comment]
Este problema se da por que el nombre que figura en la descripción proyecto y el nombre de la carpeta root del repositorio del proyecto difieren.

Verificar que:

![image](https://user-images.githubusercontent.com/11511177/55006479-985a2000-4fbc-11e9-9146-b288751b042e.png)

y...

![image](https://user-images.githubusercontent.com/11511177/55006600-c475a100-4fbc-11e9-8128-f33443b19176.png)

Coincidan.

**Comment by asanzo** [comment]
Probé con el otro plugin de Git y me lo importó con el nombre del .project. 

¿No se puede resolver con algún default? No tengo en claro cuál default me gusta más, si el nombre del repo ó del project. Creo q lo segundo es más correcto.

**Comment by 51lv3str1** [comment]
Esto esta solucionado en la versión actual de Sgit. Ahora, el se actualiza de forma correcta el nombre del proyecto en el .project.

**Comment by npasserini** [comment]
@fdodino tal vez nos podría dar una mano para verificar qué es lo que hace
que se nos mezclen las cosas.
Normalmente no debería ser un problema que esos nombres difieran.

**Comment by fdodino** [comment]
Hola! no entiendo muy bien si ya lo solucionaron, a lo que decía @asanzo , en general siempre vale lo que dice la definición del proyecto y no la del repo. Sea un `.project`, un archivo `pom.xml`, o un `package.json` de npm. Igual no se si me necesitan para algo, este sábado nos vemos.
