### ISSUE TITLE
La vista de SGit podría llamarse "Git Simple" ó algo así.

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/SGit#5]
![Selección_999(165)](https://user-images.githubusercontent.com/5421992/54948777-42ce3680-4f1c-11e9-88d2-cf0be7b57c97.png)

Es decir, estaría bueno que los alumnos pudieran diferenciar cuál usar.

**Comment by 51lv3str1** [comment]
Me gusta Git Simplificado. Se escuchan otras propuestas.

**Comment by npasserini** [comment]
+1

**Comment by 51lv3str1** [comment]
hecho
